# Generated by Django 3.2 on 2021-04-08 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, '技术类'), (1, '管理类'), (2, '运营类'), (3, '销售类')], verbose_name='职位类别')),
                ('job_name', models.CharField(max_length=200, verbose_name='职位名称')),
                ('job_city', models.SmallIntegerField(choices=[(0, '北京'), (1, '大连'), (2, '上海')], verbose_name='工作地点')),
                ('job_duty', models.TextField(max_length=1200, verbose_name='职位职责')),
                ('job_require', models.TextField(max_length=1200, verbose_name='职位要求')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('upgrade_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
                'db_table': 'tb_job',
            },
        ),
    ]
