# Generated by Django 3.2 on 2021-04-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='apply_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job', verbose_name='应聘职位'),
        ),
    ]
